version: '3.8'

services:
  cine-pulse:
    build: .
    container_name: cine-pulse-app
    environment:
      - DATA_PATH=/data
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - RUN_MODE=scheduler
      - RUN_AT_STARTUP=true
      - SOURCE_URLS=${SOURCE_URLS:-["https://nkiri.com/"]}
      # Email notification settings with Mailtrap
      - EMAIL_SMTP_HOST=${EMAIL_SMTP_HOST:-live.smtp.mailtrap.io}
      - EMAIL_SMTP_PORT=${EMAIL_SMTP_PORT:-587}
      - EMAIL_SENDER=${EMAIL_SENDER:-""}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD:-""}
      - EMAIL_RECIPIENT=${EMAIL_RECIPIENT:-""}
    volumes:
      - cine_pulse_data:/data
      - ./logs:/app/logs
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - cine-pulse-network

  # Optional: SQLite browser for database management (development only)
  sqlite-browser:
    image: coleifer/sqlite-web
    container_name: cine-pulse-sqlite-browser
    ports:
      - "8081:8080"
    volumes:
      - cine_pulse_data:/data
    command: ["sqlite_web", "/data/cine_pulse.db", "--host", "0.0.0.0"]
    depends_on:
      - cine-pulse
    profiles:
      - dev
    networks:
      - cine-pulse-network

volumes:
  cine_pulse_data:
    driver: local

networks:
  cine-pulse-network:
    driver: bridge
